name: Run textlint

on:
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run textlint
        run: |
          pnpm run textlint
